export default {
    name: "Andrés Gutiérrez Hurtado",
    age: new Date().getFullYear() - 2007,
    email: "andres52885241@gmail.com",
    github: "https://github.com/AndresGutierrezHurtado",
    linkedin: "https://www.linkedin.com/in/andr%C3%A9s-guti%C3%A9rrez-hurtado-25946728b/",
    instagram: "https://www.instagram.com/andres52885241/",
    stats: {
        commitsCount: 1300,
        websitesBuilt: 15,
        certificationsCount: 30,
        yearsOfExperience: 1,
    },
    certificates: [
        {
            institution: "Netzun",
            title: "Especialización en Desarrollo Web",
            date: new Date("2025-03-01"),
            image: "https://media.licdn.com/dms/image/v2/D4E2DAQGLG7wTwOPoiQ/profile-treasury-document-images_800/B4EZWWjhftHUAo-/1/1741987650810?e=1743638400&v=beta&t=VFk4bwm70cc6hMwGuUcQw-lrpaqfl5JEflYA6TgxUFo",
            link: "https://github.com",
        },
        {
            institution: "Netzun",
            title: "Especializacion en SQL",
            date: new Date("2025-03-01"),
            image: "https://media.licdn.com/dms/image/v2/D4E2DAQGeBqGD5eFJfw/profile-treasury-document-images_800/B4EZWWisbwGYAo-/1/1741987433549?e=1743638400&v=beta&t=7Q7JttxfN_vgGrUQcUYECrigF-rrw8tsKlB_3GkZhCo",
            link: "https://github.com",
        },
        {
            institution: "Platzi",
            title: "Docker Avanzado",
            date: new Date("2025-03-01"),
            image: "https://media.licdn.com/dms/image/v2/D4E2DAQEw9VgP8ZRHvw/profile-treasury-document-images_800/B4EZWWuq1IG0Ak-/1/1741990573530?e=1743638400&v=beta&t=KqsF5Nf5lP5vfTaLk1cAN_pNWOEBcK9w5FvkJA28-xs",
            link: "https://github.com",
        },
        {
            institution: "Hacker Rank",
            title: "REST API Intermediate",
            date: new Date("2025-03-01"),
            image: "https://media.licdn.com/dms/image/v2/D4E2DAQEMscv8UL32_w/profile-treasury-document-images_800/B4EZWWpsiNGwAk-/1/1741989270587?e=1743638400&v=beta&t=v5kPOUbXtervibqp-P1dPD0QTVxkk1zOnKUccQPSg_E",
            link: "https://github.com",
        },
        {
            institution: "Servicio Nacional de Aprendizaje",
            title: "Desarrollo Web con PHP",
            date: new Date("2023-12-01"),
            image: "https://media.licdn.com/dms/image/v2/D4E2DAQG7yWjk4KSIRA/profile-treasury-document-images_800/B4EZWWrm8iGYAk-/1/1741989770065?e=1743638400&v=beta&t=ubXnQnvJhfB_YWifCcz4QmxfwUmVnnRmswnQ1_AQyV0",
            link: "https://github.com",
        },
        {
            institution: "Platzi",
            title: "Introducción a DevOps",
            date: new Date("2025-03-01"),
            image: "https://media.licdn.com/dms/image/v2/D4D2DAQH6xigd7zfz9w/profile-treasury-document-images_800/B4DZWiviTqHYAk-/1/1742192127274?e=1743638400&v=beta&t=3LrGAUyWLHAKSrIu-fjB9KvpHXNc-FsUlqChm_aDmo4",
            link: "https://github.com",
        },
    ],
    projects: [
        {
            name: "AC Computers",
            description:
                "A web application for selling PCs and components. It allows users to view the catalog, search for products. It also has a section for contact form.",
            image: "/projects/ac-computers.png",
            link: "https://ac-computers-react.vercel.app/",
            github: "https://github.com/AndresGutierrezHurtado/ac-computers-react",
            tags: ["Next.js", "Three.js", "Tailwind CSS", "Postgres", "Docker", "Sequelize"],
            medias: [],
        },
        {
            name: "Express Sale",
            description:
                "A web application for neighborhood stores. It allows users to view the catalog, search for products, place orders, view delivery status and view statistics.",
            image: "/projects/express-sale.png",
            link: "https://tempus-elite.onrender.com/",
            github: "https://github.com/AndresGutierrezHurtado/relojeria",
            tags: ["Laravel", "MySQL", "Tailwind CSS", "Docker", "Sequelize"],
            medias: [],
        },
        {
            name: "Tempus Elite",
            description:
                "A web application for selling watches. It allows users to view the catalog, search for watches.",
            image: "/projects/tempus-elite.png",
            link: "https://tempus-elite.onrender.com/",
            github: "https://github.com/AndresGutierrezHurtado/relojeria",
            tags: ["Next.js", "Three.js", "Tailwind CSS", "Cheerio", "Docker", "Sequelize"],
            medias: [],
        },
        {
            name: "Uniformes Escolares la Abejita 22",
            description:
                "A web application for selling watches. It allows users to view the catalog, search for watches.",
            image: "/projects/la-abejita.png",
            link: "https://tempus-elite.onrender.com/",
            github: "https://github.com/AndresGutierrezHurtado/relojeria",
            tags: ["Laravel", "MySQL", "Tailwind CSS", "Docker", "Sequelize"],
            medias: [],
        },
    ],
    experiences: [
        {
            company: "Plataforma AV",
            title: "Junior Developer",
            description:
                "I will be doing my technologist internship at Plataforma AV, where I will contribute by developing the required software solutions to support the company's needs.",
            dateStart: new Date("2025-06-15"),
            dateEnd: new Date("2025-12-15"),
            tags: ["HTML", "CSS", "JavaScript"],
        },
        {
            company: "AC Computers",
            title: "Software Analist and Developer",
            description:
                "I collaborated with AC Computers to develop their online product catalog, enhancing their web presence and improving customer accessibility. I worked on the design and implementation of a responsive and user-friendly interface, ensuring an intuitive browsing experience.",
            dateStart: new Date("2025-01-15"),
            dateEnd: new Date("2025-06-15"),
            tags: ["HTML", "CSS", "JavaScript"],
        },
        {
            company: "SENNOVA",
            title: "Monitor | Software Analist and Developer",
            description:
                "I worked on the Spanish documentation of the WCAG 2.1, creating guides and examples to facilitate its implementation. I developed a web accessibility tool for React projects. I presented this project at conferences and events, highlighting the importance of digital accessibility.",
            dateStart: new Date("2024-08-15"),
            dateEnd: new Date("2024-12-15"),
            tags: ["HTML", "CSS", "JavaScript"],
        },
    ],
    techStack: [
        "HTML",
        "CSS",
        "JavaScript",
        "PHP",
        "MySQL",
        "MongoDB",
        "React",
        "Next.js",
        "Node.js",
        "Express.js",
        "Laravel",
        "Sequelize",
        "Socket.io",
        "GitHub",
        "Figma",
        "Postman",
        "TailwindCSS",
        "Bootstrap",
    ],
};
