const techList = [
    {
        name: "HTML",
        icon: "HTMLIcon",
        background: "bg-amber-500/20",
        color: "text-amber-500",
        border: "border-amber-500",
    },
    {
        name: "CSS",
        icon: "CSSIcon",
        background: "bg-blue-500/20",
        color: "text-blue-500",
        border: "border-blue-500",
    },
    {
        name: "PHP",
        icon: "PHPIcon",
        background: "bg-fuchsia-800/20",
        color: "text-fuchsia-800",
        border: "border-fuchsia-800",
    },
    {
        name: "MySQL",
        icon: "MySQLIcon",
        background: "bg-teal-500/20",
        color: "text-teal-500",
        border: "border-teal-500",
    },
    {
        name: "MongoDB",
        icon: "MongoDBIcon",
        background: "bg-green-500/20",
        color: "text-green-500",
        border: "border-green-500",
    },
    {
        name: "React",
        icon: "ReactIcon",
        background: "bg-sky-500/20",
        color: "text-sky-500",
        border: "border-sky-500",
    },
    {
        name: "Next.js",
        icon: "NextIcon",
        background: "bg-gray-900/20",
        color: "text-gray-900",
        border: "border-gray-900",
    },
    {
        name: "Node.js",
        icon: "NodeIcon",
        background: "bg-lime-500/20",
        color: "text-lime-500",
        border: "border-lime-500",
    },
    {
        name: "Laravel",
        icon: "LaravelIcon",
        background: "bg-red-600/20",
        color: "text-red-600",
        border: "border-red-600",
    },
    {
        name: "Sequelize",
        icon: "SequelizeIcon",
        background: "bg-sky-500/20",
        color: "text-sky-500",
        border: "border-sky-500",
    },
    {
        name: "Socket.io",
        icon: "SocketIcon",
        background: "bg-gray-900/20",
        color: "text-gray-900",
        border: "border-gray-900",
    },
    {
        name: "GitHub",
        icon: "GithubIcon",
        background: "bg-gray-900/20",
        color: "text-gray-900",
        border: "border-gray-900",
    },
    {
        name: "Figma",
        icon: "FigmaIcon",
        background: "bg-red-500/20",
        color: "text-red-500",
        border: "border-red-500",
    },
    {
        name: "Postman",
        icon: "PostmanIcon",
        background: "bg-orange-500/20",
        color: "text-orange-500",
        border: "border-orange-500",
    },
    {
        name: "JavaScript",
        icon: "JavaScriptIcon",
        background: "bg-yellow-500/20",
        color: "text-yellow-500",
        border: "border-yellow-500",
    },
    {
        name: "Express.js",
        icon: "ExpressIcon",
        background: "bg-gray-950/20",
        color: "text-gray-950",
        border: "border-gray-950",
    },
    {
        name: "TailwindCSS",
        icon: "TailwindCSSIcon",
        background: "bg-cyan-500/20",
        color: "text-cyan-500",
        border: "border-cyan-500",
    },
    {
        name: "Bootstrap",
        icon: "BootstrapIcon",
        background: "bg-purple-800/20",
        color: "text-purple-800",
        border: "border-purple-800",
    },
    {
        name: "Docker",
        icon: "DockerIcon",
        background: "bg-cyan-500/20",
        color: "text-cyan-500",
        border: "border-cyan-500",
    },
    {
        name: "Three.js",
        icon: "ThreeIcon",
        background: "bg-gray-950/20",
        color: "text-gray-950",
        border: "border-gray-950",
    },
    {
        name: "Cheerio",
        icon: "CheerioIcon",
        background: "bg-orange-500/20",
        color: "text-orange-500",
        border: "border-orange-500",
    },
    {
        name: "Postgres",
        icon: "PostgresIcon",
        background: "bg-sky-700/20",
        color: "text-sky-700",
        border: "border-sky-700",
    },
];

export default {
    name: "Andrés Gutiérrez Hurtado",
    age: new Date().getFullYear() - 2007,
    email: "andres52885241@gmail.com",
    github: "https://github.com/AndresGutierrezHurtado",
    linkedin: "https://www.linkedin.com/in/andr%C3%A9s-guti%C3%A9rrez-hurtado-25946728b",
    stats: {
        commitsCount: 2100,
        websitesBuilt: 15,
        certificationsCount: 30,
        yearsOfExperience: 1,
    },
    experiences: [
        {
            company: "Plataforma AV",
            title: "experience.plataforma_av.title",
            description: "experience.plataforma_av.description",
            dateStart: new Date("2025-06-15"),
            dateEnd: new Date("2025-12-15"),
        },
        {
            company: "AC Computers",
            title: "experience.ac_computers.title",
            description: "experience.ac_computers.description",
            dateStart: new Date("2025-01-15"),
            dateEnd: new Date("2025-06-15"),
        },
        {
            company: "SENNOVA",
            title: "experience.sennova.title",
            description: "experience.sennova.description",
            dateStart: new Date("2024-08-15"),
            dateEnd: new Date("2024-12-15"),
        },
        {
            company: "Uniformes La Abejita 22",
            title: "experience.uniformes_la_abejita.title",
            description: "experience.uniformes_la_abejita.description",
            dateStart: new Date("2023-05-01"),
            dateEnd: new Date("2023-12-31"),
        },
    ],
    projects: [
        {
            name: "projects.sena_accessiblity.name",
            description: "projects.sena_accessiblity.description",
            image: "/projects/sena-accessibility.png",
            link: "https://www.npmjs.com/package/sena-accessibility",
            github: "https://github.com/AndresGutierrezHurtado/sena-accessibility",
            tags: techList.filter((s) => ["JavaScript", "Node.js", "TailwindCSS"].includes(s.name)),
            medias: [],
        },
        {
            name: "projects.eduweb.name",
            description: "projects.eduweb.description",
            image: "/projects/eduweb.png",
            link: null,
            github: "https://github.com/AndresGutierrezHurtado/eduweb",
            tags: techList.filter((s) =>
                ["Next.js", "TailwindCSS", "Sequelize", "MySQL"].includes(s.name)
            ),
            medias: [],
        },
        {
            name: "projects.ac_computers.name",
            description: "projects.ac_computers.description",
            image: "/projects/ac-computers.png",
            link: "https://ac-computers-react.vercel.app/",
            github: "https://github.com/AndresGutierrezHurtado/ac-computers",
            tags: techList.filter((s) =>
                ["Next.js", "Three.js", "TailwindCSS", "Postgres", "Docker", "Sequelize"].includes(
                    s.name
                )
            ),
            medias: [],
        },
        {
            name: "projects.tempus_elite.name",
            description: "projects.tempus_elite.description",
            image: "/projects/tempus-elite.png",
            link: "https://tempus-elite.onrender.com/",
            github: "https://github.com/AndresGutierrezHurtado/relojeria",
            tags: techList.filter((s) =>
                ["Next.js", "Three.js", "TailwindCSS", "Cheerio", "Sequelize"].includes(s.name)
            ),
            medias: [],
        },
        {
            name: "projects.isa_making.name",
            description: "projects.isa_making.description",
            image: "/projects/isa-making.png",
            link: null,
            github: "https://github.com/AndresGutierrezHurtado/isa-making",
            tags: techList.filter((s) =>
                ["Next.js", "TailwindCSS", "Sequelize", "MySQL"].includes(s.name)
            ),
            medias: [],
        },
        {
            name: "projects.express_sale.name",
            description: "projects.express_sale.description",
            image: "/projects/express-sale.png",
            link: null,
            github: "https://github.com/AndresGutierrezHurtado/express-sale",
            tags: techList.filter((s) =>
                ["React", "Node.js", "Express.js", "MySQL", "TailwindCSS", "Sequelize"].includes(
                    s.name
                )
            ),
            medias: [],
        },
        {
            name: "projects.la_abejita.name",
            description: "projects.la_abejita.description",
            image: "/projects/la-abejita.png",
            link: null,
            github: "https://github.com/AndresGutierrezHurtado/la-abejita-22",
            tags: techList.filter((s) => ["Laravel", "MySQL", "TailwindCSS"].includes(s.name)),
            medias: [],
        },
    ],
    certificates: [
        {
            institution: "Netzun",
            title: "Especialización en Programación Web",
            date: new Date("2025-03-01"),
            image: "/certificates/especializacion-programacion.jpg",
            link: "https://www.linkedin.com/in/andr%C3%A9s-guti%C3%A9rrez-hurtado-25946728b/details/certifications/378440196/multiple-media-viewer/?profileId=ACoAAEZedqUBV_yoiCgh0sb7NctvIQhDuO90MoU&treasuryMediaId=1741987679214",
        },
        {
            institution: "Netzun",
            title: "Especializacion en SQL",
            date: new Date("2025-03-01"),
            image: "/certificates/especializacion-sql.jpg",
            link: "https://www.linkedin.com/in/andr%C3%A9s-guti%C3%A9rrez-hurtado-25946728b/details/certifications/378056478/multiple-media-viewer/?profileId=ACoAAEZedqUBV_yoiCgh0sb7NctvIQhDuO90MoU&treasuryMediaId=1741987557089",
        },
        {
            institution: "Platzi",
            title: "Docker Avanzado",
            date: new Date("2025-03-01"),
            image: "/certificates/docker-avanzado.jpg",
            link: "https://www.linkedin.com/in/andr%C3%A9s-guti%C3%A9rrez-hurtado-25946728b/details/certifications/381369706/multiple-media-viewer/?profileId=ACoAAEZedqUBV_yoiCgh0sb7NctvIQhDuO90MoU&treasuryMediaId=1741990608965",
        },
        {
            institution: "Hacker Rank",
            title: "REST API Intermediate",
            date: new Date("2025-03-01"),
            image: "/certificates/rest-api.jpg",
            link: "https://www.linkedin.com/in/andr%C3%A9s-guti%C3%A9rrez-hurtado-25946728b/details/certifications/379906194/multiple-media-viewer/?profileId=ACoAAEZedqUBV_yoiCgh0sb7NctvIQhDuO90MoU&treasuryMediaId=1741989352942",
        },
        {
            institution: "Servicio Nacional de Aprendizaje",
            title: "Desarrollo Web con PHP",
            date: new Date("2023-12-01"),
            image: "/certificates/desarrollo-php.jpg",
            link: "https://www.linkedin.com/in/andr%C3%A9s-guti%C3%A9rrez-hurtado-25946728b/details/certifications/1741989779906/single-media-viewer/?profileId=ACoAAEZedqUBV_yoiCgh0sb7NctvIQhDuO90MoU",
        },
        {
            institution: "Platzi",
            title: "Introducción a DevOps",
            date: new Date("2025-03-01"),
            image: "/certificates/intro-devops.jpg",
            link: "https://www.linkedin.com/in/andr%C3%A9s-guti%C3%A9rrez-hurtado-25946728b/details/certifications/1742192134766/single-media-viewer/?profileId=ACoAAEZedqUBV_yoiCgh0sb7NctvIQhDuO90MoU",
        },
    ],
    techStack: techList.filter((s) =>
        [
            "HTML",
            "CSS",
            "JavaScript",
            "PHP",
            "MySQL",
            "MongoDB",
            "React",
            "Next.js",
            "Node.js",
            "Express.js",
            "Laravel",
            "Sequelize",
            "Socket.io",
            "GitHub",
            "Figma",
            "Postman",
            "TailwindCSS",
            "Bootstrap",
        ].includes(s.name)
    ),
};
