import { Passion_One, Inter } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";

import Header from "@/layout/header";
import Footer from "@/layout/footer";

import "./globals.css";

const passionOne = Passion_One({
    variable: "--font-passion-one",
    subsets: ["latin"],
    weight: ["700"],
});

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const locale = await getLocale();

    return (
        <html lang={locale}>
            <NextIntlClientProvider locale={locale}>
                <body
                    className={`${passionOne.variable} ${inter.variable} antialiased flex flex-col min-h-screen`}
                >
                    <Header />
                    <main className="flex-1">{children}</main>
                    <Footer />
                </body>
            </NextIntlClientProvider>
        </html>
    );
}
