import { Passion_One, Inter } from "next/font/google";
import "./globals.css";

const passionOne = Passion_One({
    variable: "--font-passion-one",
    subsets: ["latin"],
    weight: ["700"],
});

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
    weight: ["400", "700"], 
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${passionOne.variable} ${inter.variable} antialiased`}>
                {children}
            </body>
        </html>
    );
}
