import { Passion_One, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/layout/header";
import Footer from "@/layout/footer";

const passionOne = Passion_One({
    variable: "--font-passion-one",
    subsets: ["latin"],
    weight: ["700"],
});

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${passionOne.variable} ${inter.variable} antialiased flex flex-col min-h-screen`}>
                <Header />
                <main className="flex-1">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
